export const DEFAULT_CATEGORIES = [
  { name: "Activity", icon: "activity" },
  { name: "Gift", icon: "gift" },
  { name: "Restaurant", icon: "restaurant" },
  { name: "Travel", icon: "travel" },
  { name: "Valentine Day", icon: "valentine" },
  { name: "Board Game", icon: "dice" },
  { name: "Movies", icon: "movie" },
  { name: "Workout", icon: "workout" },
  { name: "Cooking", icon: "cooking" },
  { name: "Misc", icon: "misc" },
  { name: "Music", icon: "music" },
  { name: "Coffee", icon: "coffee" },
  { name: "Books", icon: "book" },
  { name: "Shopping", icon: "shopping" },
  { name: "Gaming", icon: "gamepad" },
  { name: "Outdoor", icon: "sun" },
  { name: "Night Out", icon: "moon" },
  { name: "Favorites", icon: "star" },
  { name: "Places", icon: "map-pin" },
  { name: "Cycling", icon: "bike" },
  { name: "Camping", icon: "tent" },
  { name: "Art", icon: "palette-brush" },
  { name: "Pets", icon: "pet" },
  { name: "Wellness", icon: "spa" },
  { name: "Party", icon: "party" },
  { name: "Beach", icon: "beach" },
  { name: "Photography", icon: "photo" },
  { name: "Garden", icon: "garden" },
  { name: "Wine & Dine", icon: "wine" },
  { name: "Puzzle", icon: "puzzle" },
  { name: "Fitness", icon: "dumbbell" },
  { name: "Headphones", icon: "headphones" },
  { name: "Painting", icon: "paintbrush" },
  { name: "Navigation", icon: "navigation" },
  { name: "Calendar", icon: "calendar" },
  { name: "Camera", icon: "camera" },
  { name: "Download", icon: "download" },
  { name: "Upload", icon: "upload" },
  { name: "Palette", icon: "palette" },
  { name: "Globe", icon: "globe" },
  { name: "Monitor", icon: "monitor" },
  { name: "Picked", icon: "picked" },
  { name: "Vault", icon: "vault" },
  { name: "Clock", icon: "clock" },
  { name: "Users", icon: "users" },
  { name: "Edit", icon: "edit" },
  { name: "Image", icon: "image" },
  { name: "Thermometer", icon: "thermometer" },
  { name: "Info", icon: "info" },
  { name: "Home", icon: "home" },
] as const;

export const CATEGORY_ICON_MAP: Record<string, string> = Object.fromEntries(
  DEFAULT_CATEGORIES.map((c) => [c.name, c.icon]),
);
